export const shoppingPageSelectors = {
      addToCartButton: ".add_to_cart_button",
      couponInput: "#coupon_code",
      applyCouponButton: "button[name='apply_coupon']",
      cartLink: "Koszyk",
      proceedToPaymentButton: "Przejdź do płatności",
      firstNameInput: "#billing_first_name",
      lastNameInput: "#billing_last_name",
      cartButton: '.menu-item-200',
      addressInput: "#billing_address_1",
      postcodeInput: "#billing_postcode",
      cityInput: "#billing_city",
      phoneInput: "#billing_phone",
      emailInput: "#billing_email",
      iframe: "iframe",
      termsCheckbox: "#terms",
      placeOrderButton: "#place_order",
      successMessage: "Dziękujemy. Otrzymaliśmy Twoje zamówienie.",
      removeFromCartButton: '.remove[data-product_id="386"]',
      restoreButton: '.restore-item',
    };